on:
  push:
    branches:
      - main

name: Publish Extension

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0

      - name: Automatic GitHub Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release

      - name: Publish
        uses: lannonbr/vsce-action@3.0.0
        if: steps.release.outputs.released == 'true'
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
